---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'one-ring'
SiteConfig:
  extensions:
    - SiteConfigExtension
Director:
  environment_type: 'dev'

---
Only:
  environment: dev
---
Email:
  send_all_emails_to: 'allen@easymode.com.au'