language: php
php:
  - 5.3
env:
  global:
    - DB=mysql
    - "FTP_USER=ss@ss.easymode.com.au"
    - "FTP_PASS=871210"
after_success:
    - chmod +x deploy.sh
    - sh deploy.sh
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS ss_official;" -uroot -ppassword; fi
  - composer update
  - php framework/cli-script.php dev/build flush=all
  - cd tests
script: phpunit -v