language: php
php:
  - 5.3
env:
  global:
    - "FTP_USER=ss@ss.easymode.com.au"
    - "FTP_PASS=admin!12"
    - DB=MYSQL CORE_RELEASE=3.3
before_script:
#  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS handy_service;" -uroot -ppassword; fi
#  - composer install
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
#  - composer install

script:
  - phpunit --configuration ~/builds/ss/phpunit.xml
#after_success:
#  - chmod a+x ./deploy.sh
#  - ./deploy.sh
