language: php
php:
  - 5.3
env:
  global:
    - DB=mysql
    - "FTP_USER=ss@ss.easymode.com.au"
    - "FTP_PASSWORD=871210"
after_success:
    "curl -T bower.json -u $FTP_USER:$FTP_PASSWORD ftp://easymode.com.au/"
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS ss_official;" -uroot -ppassword; fi
  - composer update
  - cd tests
script: phpunit -v